// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: haqq/ethiq/v1/ethiq.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the ethiq module.
type Params struct {
	// enabled defines whether the module is enabled
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// start_rate defines the starting price rate
	StartRate cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=start_rate,json=startRate,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"start_rate"`
	// curve_coefficient defines the curve coefficient for the bonding curve
	CurveCoefficient cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=curve_coefficient,json=curveCoefficient,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"curve_coefficient"`
	// power_coefficient defines the power coefficient for the bonding curve
	PowerCoefficient cosmossdk_io_math.LegacyDec `protobuf:"bytes,4,opt,name=power_coefficient,json=powerCoefficient,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"power_coefficient"`
	// min_mint_per_tx defines the minimum amount that can be minted per transaction
	MinMintPerTx cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=min_mint_per_tx,json=minMintPerTx,proto3,customtype=cosmossdk.io/math.Int" json:"min_mint_per_tx"`
	// max_mint_per_tx defines the maximum amount that can be minted per transaction
	MaxMintPerTx cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=max_mint_per_tx,json=maxMintPerTx,proto3,customtype=cosmossdk.io/math.Int" json:"max_mint_per_tx"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_344776ff2d01262c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Params)(nil), "haqq.ethiq.v1.Params")
}

func init() { proto.RegisterFile("haqq/ethiq/v1/ethiq.proto", fileDescriptor_344776ff2d01262c) }

var fileDescriptor_344776ff2d01262c = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0xd2, 0xcd, 0x4e, 0xea, 0x40,
	0x14, 0x07, 0xf0, 0xf6, 0x72, 0x2f, 0xf7, 0xd2, 0x5c, 0xa3, 0x54, 0x4d, 0x0a, 0x26, 0x2d, 0x61,
	0x45, 0x48, 0x6c, 0x43, 0xdc, 0xb9, 0x44, 0x12, 0x43, 0xa2, 0x09, 0x21, 0xba, 0x71, 0xd3, 0x0c,
	0x65, 0x68, 0x27, 0x38, 0x33, 0x65, 0x3a, 0x40, 0x79, 0x03, 0xe3, 0xca, 0x47, 0x60, 0xe9, 0x92,
	0xc7, 0x60, 0x89, 0x3b, 0xe3, 0x82, 0x18, 0x58, 0xe0, 0x63, 0x98, 0xce, 0xe0, 0x07, 0x71, 0xc5,
	0xa6, 0x39, 0xe7, 0xfc, 0x7b, 0x7e, 0x5d, 0xf4, 0x68, 0xb9, 0x00, 0xf4, 0x7a, 0x0e, 0xe4, 0x01,
	0xea, 0x39, 0x83, 0x8a, 0x2c, 0xec, 0x90, 0x51, 0x4e, 0xf5, 0x9d, 0x24, 0xb2, 0xe5, 0x64, 0x50,
	0xc9, 0x1f, 0xf8, 0xd4, 0xa7, 0x22, 0x71, 0x92, 0x4a, 0xbe, 0x94, 0xcf, 0x79, 0x34, 0xc2, 0x34,
	0x72, 0x65, 0x20, 0x9b, 0x75, 0x94, 0x05, 0x18, 0x11, 0xea, 0x88, 0xa7, 0x1c, 0x15, 0x9f, 0x52,
	0x5a, 0xba, 0x01, 0x18, 0xc0, 0x91, 0x6e, 0x68, 0x7f, 0x21, 0x01, 0xad, 0x5b, 0xd8, 0x36, 0xd4,
	0x82, 0x5a, 0xfa, 0xd7, 0xfc, 0x68, 0xf5, 0x73, 0x4d, 0x8b, 0x38, 0x60, 0xdc, 0x65, 0x80, 0x43,
	0xe3, 0x57, 0x41, 0x2d, 0x65, 0xaa, 0xa5, 0xe9, 0xdc, 0x52, 0x5e, 0xe6, 0xd6, 0x91, 0xfc, 0x42,
	0xd4, 0xee, 0xda, 0x88, 0x3a, 0x18, 0xf0, 0xc0, 0xbe, 0x80, 0x3e, 0xf0, 0x46, 0x35, 0xe8, 0x3d,
	0xae, 0x26, 0x65, 0xb5, 0x99, 0x11, 0xbb, 0x4d, 0xc0, 0xa1, 0x7e, 0xad, 0x65, 0xbd, 0x3e, 0x1b,
	0x40, 0xd7, 0xa3, 0xb0, 0xd3, 0x41, 0x1e, 0x82, 0x84, 0x1b, 0xa9, 0x2d, 0xbd, 0x3d, 0x41, 0x9c,
	0x7d, 0x09, 0x09, 0x1b, 0xd2, 0x21, 0x64, 0x1b, 0xec, 0xef, 0x6d, 0x59, 0x41, 0x7c, 0x67, 0xeb,
	0xda, 0x2e, 0x46, 0xc4, 0xc5, 0x88, 0x70, 0x37, 0x84, 0xcc, 0xe5, 0xb1, 0xf1, 0x47, 0xa0, 0xc5,
	0x35, 0x7a, 0xf8, 0x13, 0xad, 0x13, 0x2e, 0xb9, 0xff, 0x18, 0x91, 0x4b, 0x44, 0x78, 0x03, 0xb2,
	0xab, 0x58, 0x50, 0x20, 0xde, 0xa0, 0xd2, 0x5b, 0x50, 0x20, 0xfe, 0xa4, 0x4e, 0x0b, 0x77, 0x63,
	0x4b, 0x79, 0x1b, 0x5b, 0xca, 0xfd, 0x6a, 0x52, 0xde, 0x17, 0xc7, 0x12, 0xaf, 0xcf, 0x45, 0xfe,
	0xc8, 0x6a, 0x6d, 0xba, 0x30, 0xd5, 0xd9, 0xc2, 0x54, 0x5f, 0x17, 0xa6, 0xfa, 0xb0, 0x34, 0x95,
	0xd9, 0xd2, 0x54, 0x9e, 0x97, 0xa6, 0x72, 0x53, 0xf6, 0x11, 0x0f, 0xfa, 0x2d, 0xdb, 0xa3, 0xd8,
	0x49, 0x36, 0x8f, 0x09, 0xe4, 0x43, 0xca, 0xba, 0xce, 0x06, 0xc3, 0x47, 0x21, 0x8c, 0x5a, 0x69,
	0x71, 0x20, 0x27, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0x51, 0xcd, 0x16, 0x20, 0x90, 0x02, 0x00,
	0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MaxMintPerTx.Size()
		i -= size
		if _, err := m.MaxMintPerTx.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthiq(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.MinMintPerTx.Size()
		i -= size
		if _, err := m.MinMintPerTx.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthiq(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.PowerCoefficient.Size()
		i -= size
		if _, err := m.PowerCoefficient.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthiq(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.CurveCoefficient.Size()
		i -= size
		if _, err := m.CurveCoefficient.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthiq(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.StartRate.Size()
		i -= size
		if _, err := m.StartRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintEthiq(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEthiq(dAtA []byte, offset int, v uint64) int {
	offset -= sovEthiq(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = m.StartRate.Size()
	n += 1 + l + sovEthiq(uint64(l))
	l = m.CurveCoefficient.Size()
	n += 1 + l + sovEthiq(uint64(l))
	l = m.PowerCoefficient.Size()
	n += 1 + l + sovEthiq(uint64(l))
	l = m.MinMintPerTx.Size()
	n += 1 + l + sovEthiq(uint64(l))
	l = m.MaxMintPerTx.Size()
	n += 1 + l + sovEthiq(uint64(l))
	return n
}

func sovEthiq(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEthiq(x uint64) (n int) {
	return sovEthiq(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEthiq
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthiq
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthiq
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StartRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurveCoefficient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthiq
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthiq
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.CurveCoefficient.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PowerCoefficient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthiq
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthiq
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PowerCoefficient.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinMintPerTx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthiq
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthiq
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinMintPerTx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxMintPerTx", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEthiq
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEthiq
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxMintPerTx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEthiq(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEthiq
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEthiq(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEthiq
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEthiq
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEthiq
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEthiq
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEthiq
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEthiq        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEthiq          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEthiq = fmt.Errorf("proto: unexpected end of group")
)
