name: dry-run-goreleaser

on:
    pull_request:
    push:
      branches:
        - master

jobs:
  dry-run-goreleaser:
    runs-on: ubuntu-cpu16-ram64
    environment: release
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
      - name: Pull LFS files
        run: git lfs pull
      - name: release dry run
        run: make release-dry-run
