name: Nix
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  nix-flake-check:
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@v4
      - name: Run flake check
        run: |
          nix flake check --impure
