name: Protobuf
# Protobuf runs buf (https://buf.build/) lint and check-breakage
# This workflow is only run when a .proto file has been changed
on:
  workflow_dispatch:
  pull_request:

jobs:
  proto-pass:
    name: Proto Pass
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
      # - break-check
    steps:
      - run: exit 0
  
  build:
    name: Check that proto builds and committed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haqq-network/nix-action@master
        with:
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
      - run: |
          nix develop --impure #ci --command ci-proto

  lint:
    name: Proto lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.28.1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"

  # NOTE: This is disabled only for this merge request, it will be enabled in master branch
  # break-check:
  #   name: Proto break-check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: bufbuild/buf-setup-action@v1.28.1
  #     - uses: bufbuild/buf-breaking-action@v1
  #       with:
  #         input: "proto"
  #         against: "https://github.com/${{ github.repository }}.git#branch=${{ github.event.pull_request.base.ref }},ref=HEAD~1,subdir=proto"
